azs:
- name: z1
  cloud_properties: {availability_zone: ((az))}
#- name: z2
#  cloud_properties: {availability_zone: us-east-2b}


# see https://bosh.io/docs/aws-cpi/#resource-pools for all aoption
vm_types:
- name: default
  cloud_properties:
    instance_type: c5.large
    ephemeral_disk: {size: 58000, type: gp2}
- name: services
  cloud_properties:
    instance_type: m4.2xlarge
    root_disk: {size: 58000, type: gp2}
    security_groups: ((default_security_groups))
    iam_instance_profile: ((iam_instance_profile))
- name: builders
  disk_size: 100_000
  cloud_properties:
    instance_type: m4.xlarge
    root_disk: {size: 55000, type: gp2}
    security_groups: ((default_security_groups))
    auto_assign_public_ip: true
    iam_instance_profile: ((iam_instance_profile))

# only used if persistent_disk_type specified for a job
disk_types:
- name: small
  disk_size: 56_000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 100_000
  cloud_properties: {type: gp2}

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    az: z1
    dns: ((internal_dns))
    reserved: [((internal_gw))/30]  #.0 - .3
    cloud_properties: {subnet: ((circle_subnet))}
  # To support multi-az services
  #- range: 10.10.64.0/24
  #  gateway: 10.10.64.1
  #  az: z2
  #  static: [10.10.64.121, 10.10.64.122]
  #  dns: [10.0.4.2]
  #  cloud_properties: {subnet: ((circle-subnet))}

  #to support elastic IPs
- name: vip
  type: vip

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
