---
name: static
director_uuid: "see aws-overrides.yml"

releases:
- name: circle-static
  version: latest  # change to github link
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3468.13 #important!! At some future release stemcells began blocking IPv6 which breaks default nginx config.
  #Need to update docker images since e we dont actulally use ipv6


update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

instance_groups:
# VM 1, runs services
- name: frontend
  instances: 1
  vm_type: services
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default #assign private IP, DNS, etc, et
    default: [dns, gateway]
  - name: vip #assign elastic IP
    static_ips: [((frontend_ip))]
  env:
    bosh:
      ipv6: {enable: true}
  jobs:
  - name: frontend
    release: circle-static
# VM 2, runs nomad fleet
- name: cluster #what we call it
  instances: 1
  vm_type: builders
  stemcell: trusty
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: nomad #name in provided release
    release: circle-static
